version: '3.4'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  web:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      APPLICATION_DB: ${APPLICATION_DB}
      POSTGRES_USER: postgres
      POSTGRES_HOSTNAME: db
      POSTGRES_PASSWORD: password
      FLASK_SECRET_KEY: dummy_secret_key
      FLASK_TRUSTED_HOSTS: ${FLASK_TRUSTED_HOSTS}
      PIPENV_DONT_LOAD_ENV: 1
    command: pipenv run flask run --host 0.0.0.0
    volumes:
      - ${PWD}:/opt/code
    ports:
      - "5000:5000"

volumes:
  pgdata:
